version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: type-coverage
    versions:
    - 2.15.0
    - 2.15.1
    - 2.16.0
    - 2.16.1
    - 2.16.2
    - 2.17.3
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.2.0
    - 24.3.5
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.16.1
    - 4.19.0
    - 4.20.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.19.0
    - 4.20.0
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.27
    - 0.20.33
    - 0.20.34
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
  - dependency-name: eslint
    versions:
    - 7.18.0
